# MODELADO DEL PROBlEMA

**Activos y Rendimientos Anuales Porcentuales:**

| Variable | Activo | Rendimiento Anual (%) |
|----------|--------|-----------------------|
| $x_1$    | MSFT   | $62.49%$                |
| $x_2$    | AMZN   | $5.09%$                 |
| $x_3$    | ADBE   | $22.30%$                |
| $x_4$    | BRK.B  | $39.37%$                |
| $x_5$    | META   | $31.12%$                |
| $x_6$    | CETES  | $11.66%$                |


### Función objetivo:
Maximizar: $0.6249x_1 + 0.0509x_2 + 0.2230x_3 + 0.3937x_4 + 0.3112x_5 + 0.1166x_6$

### Restricciones:



**Restricción de ajuste al total del Portafolio:**


$[x_1 + x_1 + x_1 + x_1 + x_1 + x_1 = 1.0]$



**Restricción de porcentaje de cada acción:** 
\begin{align*}
[x_1 &\leq 0.15] \\
[x_2 &\leq 0.15] \\
[x_3 &\leq 0.15] \\
[x_4 &\leq 0.15] \\
[x_5 &\leq 0.15] \\
\end{align*}

# SOLUCIÓN DE PROGRAMACIÓN LINEAL

In [3]:
#Definir Matrices
from scipy.optimize import linprog
import numpy as np
c = np.array([-0.6249,-0.0509,-0.2230,-0.3937, -0.3112, -0.1166])
b = np.array([0.15,0.15,0.15,0.15,0.15,1])
A = np.array([[1,0,0,0,0,0],
             [0,1,0,0,0,0],
             [0,0,1,0,0,0],
             [0,0,0,1,0,0],
             [0,0,0,0,1,0],
             [0,0,0,0,0,1]])
A_eq = np.array([[1, 1, 1, 1, 1, 1]])  
b_eq = np.array([1.0])
x_bounds = [(0, None)] *6
c,b,A

(array([-0.6249, -0.0509, -0.223 , -0.3937, -0.3112, -0.1166]),
 array([0.15, 0.15, 0.15, 0.15, 0.15, 1.  ]),
 array([[1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 1]]))

In [4]:
#Solucionar usando linprog

solucion = linprog(c, A_ub=A, b_ub=b, A_eq=A_eq, b_eq=b_eq, bounds=x_bounds, method='highs')
solucion

        message: Optimization terminated successfully. (HiGHS Status 7: Optimal)
        success: True
         status: 0
            fun: -0.27956
              x: [ 1.500e-01  0.000e+00  1.500e-01  1.500e-01  1.500e-01
                   4.000e-01]
            nit: 0
          lower:  residual: [ 1.500e-01  0.000e+00  1.500e-01  1.500e-01
                              1.500e-01  4.000e-01]
                 marginals: [ 0.000e+00  6.570e-02  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          upper:  residual: [       inf        inf        inf        inf
                                    inf        inf]
                 marginals: [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00
                              0.000e+00  0.000e+00]
          eqlin:  residual: [ 0.000e+00]
                 marginals: [-1.166e-01]
        ineqlin:  residual: [ 0.000e+00  1.500e-01  0.000e+00  0.000e+00
                              0.000e+00  6.000e-01]
                 margin